### ISSUE TITLE
Logger conflicts with built in logger

### ISSUE THREAD

**Issue by kbsoftwarellc** [anderlechtt/mos_bot#1]
Not super familiar with ruby but after downloading and setting up and trying to run it kept claiming that Logger was not a type. Google pointed out that the logger that was built into ruby and the custom one were conflicting. I ended up modifying the code locally to use the built in logger and that fixed the issue.

**Comment by Zexxx** [comment]
Hey if you could post how you fixed it that would be great. Just trying to figure ruby out hurts. @tehaon

**Comment by kbsoftwarellc** [comment]
Hopefully anderlechtt deploys an actual fix for it, but if you remove all references to the /lib/logger (which I think is like 3 files) and then replace all the Logger.p() with something like

logger = Logger.new(STDOUT)
logger.info('connected to server')

it will log everything as an info, but will show on the console and work just fine.

also a heads up, I did get banned for using this.. but I ran it for several days straight cause I didn't care if I got banned lol.

**Comment by anderlechtt** [comment]
I've also added a max_joined_channels option and set it to 5 by default to act more low key. See 32b9223263880f251335e0b3a823f9086670e0e3
